import { Job } from "./job";

export const Jobs: Job[] = [
  { id: 101,
    username: "mire180",
    email: "mirella22@april.biz",
    title: 'Mirella',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, similique.',
    category: 'independiente',
    date: '01-12-2022',
    expiration: '11-12-2022',
  },
  { id: 102,
    username: "ramirogs",
    email: "ramigs@april.biz",
    title: 'Electricista ',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, similique.',
    category: 'independiente',
    date: '01-12-2022',
    expiration: '11-12-2022',
  },
  { id: 103,
    username: "jessitwe",
    email: "jessitwe@gmail.com",
    title: 'Publicista ',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, similique.',
    category: 'agencia',
    date: '01-12-2022',
    expiration: '11-12-2022',
  },
  { id: 104,
    username: "hilary",
    email: "hilary21@april.biz",
    title: 'Gafitero ',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, similique.',
    category: 'independiente',
    date: '03-12-2022',
    expiration: '15-12-2022',
  },
  { id: 105,
    username: "leandro",
    email: "ramigs@april.biz",
    title: 'Albañil ',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, similique.',
    category: 'independiente',
    date: '05-12-2022',
    expiration: '17-12-2022',
  },
  { id: 106,
    username: "george",
    email: "george@april.biz",
    title: 'Pintor ',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, similique.',
    category: 'independiente',
    date: '08-12-2022',
    expiration: '16-12-2022',
  },
  { id: 107,
    username: "nando12",
    email: "nando12@april.biz",
    title: 'Seguridad Personal ',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, similique.',
    category: 'independiente',
    date: '12-12-2022',
    expiration: '16-12-2022',
  },
  { id: 108,
    username: "luisbj",
    email: "luisbj@april.biz",
    title: 'Sastre',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, similique.',
    category: 'independiente',
    date: '14-12-2022',
    expiration: '17-12-2022',
  },
  { id: 109,
    username: "tatiana78",
    email: "tatiana78@april.biz",
    title: 'Electricista ',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, similique.',
    category: 'independiente',
    date: '16-12-2022',
    expiration: '21-12-2022',
  },
  { id: 110,
    username: "renzo6019",
    email: "renzo6019@april.biz",
    title: 'Mecanico motos ',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, similique.',
    category: 'independiente',
    date: '11-12-2022',
    expiration: '16-12-2022',
  },
  { id: 111,
    username: "wilmertmc",
    email: "wilmertmc@april.biz",
    title: 'Mecanico autos ',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, similique.',
    category: 'independiente',
    date: '11-12-2022',
    expiration: '15-12-2022',
  },
  { id: 112,
    username: "thiago92",
    email: "thiago92@april.biz",
    title: 'Tecnico de pc',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, similique.',
    category: 'eventual',
    date: '05-12-2022',
    expiration: '12-12-2022',
  },
  { id: 113,
    username: "jimenamc",
    email: "jimenamc@april.biz",
    title: 'Digitador',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, similique.',
    category: 'independiente',
    date: '06-12-2022',
    expiration: '13-12-2022',
  },
  { id: 114,
    username: "pedro468",
    email: "pedro468@april.biz",
    title: 'Seguridad Personal ',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, similique.',
    category: 'independiente',
    date: '04-12-2022',
    expiration: '07-12-2022',
  },
  { id: 115,
    username: "bruno028",
    email: "bruno028@april.biz",
    title: 'Conductor ',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, similique.',
    category: 'agencia',
    date: '05-12-2022',
    expiration: '10-12-2022',
  },

]

